---
title: "Book Quotes"
output: github_document
---

This is a repository tracking quotes I find memorable from books I read.

___

## Contents

- [*Atomic Habits* - James Clear]
- [*Best Seat in the House* - Jack Nicklaus II & Don Yeager]
- [*Jesus and John Wayne* - Kristin Kobes Du Mez]
- [*Let My People Go Surfing* - Yvon Chouinard]
- [*The Masters: Golf, Money, and Power in Augusta, Georgia* - Curt Sampson]
- [*Why We Run: A Natural History* - Bernd Heinrich]

___

### *Atomic Habits* - James Clear

- "We all deal with setbacks but in the long run, the quality of our lives often depends on the quality of our habits." (7)
- "A very small shift in direction can lead to a very meaningful change in destination." (17)
- "Complaining about not achieving success despite working hard is like complaining about an ice cube not melting when you heated it from twenty-five to thirty-one degrees. Your work was not wasted; it is just being stored. All the action happens at thirty-two degrees." (21)
- "'When nothing seems to help, I go and look at a stonecutter hammering away at his rock, perhaps a hundred times without as much as a crack showing in it. Yet at the hundred and first blow it will split in two, and I know it was not that last blow that die it -- but all that had gone before." (21)
- "'The score takes care of itself.' The same is true for other areas of life. If you want better results, then forget about setting goals. Focus on your system instead." (24)
- "When you solve problems at the results level, you only solve them temporarily. In order to improve for good, you need to solve problems at the systems level. Fix the inputs and the outputs will fix themselves." (25)
- "It makes no sense to restrict your satisfaction to one scenario when there are many paths to success." (26)
- "The goal is not to run a marathon, the goal is to *become* a runner." (34)
- "The most practical way to change *who* you are is to change *what* you do. (38)
- "If you keep casting the same votes you've always cast, you're going to get the same results you've always had. If nothing changes, nothing is going to change." (39)
- "They make you think that you have to choose between building habits and attaining freedom. In reality, the two compliment each other." (46)
- "Environment is the invisible hand that shapes human behavior." (82)
- "You don't have to be the victim of your environment. You can also be the architect of it." (84)
- "Environment design allows you to take back control and become the architect of your life. Be the desginer of your world and not merely the consumer of it." (87)
- "In the long-run, we become a product of the environment that we live in. To put it bluntly, I have never seen someone consistently stick to positive habits in a negative environment." (94)
- "People with high self-control tend to spend less time in tempting situations. It's easier to avoid temptation than resist it." (95)
- "Ultimately, such strategies enable food scientists to find the "bliss point" for each product -- the precise combination of salt, sugar, and fat that excites your brain and keeps you coming back for more. The result, of course, is that you overeat because hyperpalatable foods are more attractive to the human brain." (103)
- "... whatever habits are normal in your culture are among the most attractive behaviors you'll find." (114)
- "The culture we live in determines which behaviors are attractive to us." (122)
- "One person might learn to reduce stress by smoking a cigarette. Another person learns to ease their anxiety by going for a run. Your current habits are not necessarily the best way to solve the problems you face; they are just the methods you learned to use. Once you associate a solution with the problem you need to solve, you keep coming back to it." (128)
- "Life feels reactive, but it is actually predictive. All day long, you are making your best guess of how to act given what you've just seen and what has worked for you in the past. You are endlessly predicting what will happen in the next moment." (129)
- "... our behavior is heavily dependent on how we interpret the events that happen to us, not necessarily the objective reality of the events themselves." (129)
- "... for many of us, a little bit of friction can be the difference between sticking with a good habit or sliding into a bad one." (158)
- "The point is to master the habit of showing up. The truth is, a habit must be established before it can be improved." (163)
- "... the costs of your good habits are in the present. The costs of your bad habits are in the future." (189)
- "... the last mile is always the least crowded." (190)
- "The first mistake is never the one that ruins you. It is the spiral of repeated mistakes that follows. Missing once is an accident. Missing twice is the start of a new habit." (201)
- "... when successful people fail, they rebound quickly. The breaking of a habit doesn't matter if the reclaiming of it is fast." (201)
- "In our data-driven world, we tend to overvalue numbers and undervalue anything ephemeral, soft, and difficult to quantify. We mistakenly think the factors we can measure are the only factors that exist. But just because you can measure something doesn't mean it's the most important thing. And just because you *can't* measure something doesn't mean it's not important at all." (203)
- "When you can't win by being better, you can win by being different." (225)
- "Boiling water will soften a potato but harden an egg. You can't control whether you're a potato or an egg, but you can decide to play a game where it's better to be hard or soft." (226)
- "Until you work as hard as those you admire, don't explain away their success as luck." (227)
- "'10 years spent learning, 4 years spent refining, and 4 years as a wild success.'" (230)
- "'Men desire novelty to such an extent that those who are doing well wish for a change as much as those who are doing badly.'" (234)
- "... everyone faces the same challenge on the journey of self-improvement: you have to fall in love with boredom." (235)
- "Anyone can work hard when they feel motivated. It's the ability to keep going when work isn't exciting that makes the difference." (237)
- "Being curious is better than being smart. Being motivated and curious counts for more than being smart because it leads to action." (261)
- "Your actions reveal how bad you want something. If you keep saying something is a priority but you never act on it, then you don't really want it. It's time to have an honest conversation with yourself. Your actions reveal your true motivations." (262)

___

### *Best Seat in the House* - Jack Nicklaus II & Don Yeager

- "Mom has always said men are simple, and they need three things: food, love, and encouragement -- and they will be fine." (95)
- "You never know what other people are going through in their lives. Even a small interaction when passing someone on a sidewalk can entirely change a person's day. Being respectful, appreciative, kind, caring, and listening to and learning from your friends, family, and strangers is very important. As big as our world is, it truly is small." (122)

___

### *Jesus and John Wayne* - Kristin Kobes Du Mez

- "... to Trump and his evangelical supporters alike, restoring white patriarchal power would make America great again." (XVI)
- "Christian nationalism -- the belief that America is God's chosen nation and must be defended as such -- serves as a powerful predictor of intolerance toward immigrants, racial minorities, and non-Christians. It is linked to opposition to gay rights and gun control, to support for harsher punishments for criminals, to justifications for the use of excessive force against black Americans in law enforcement situations, and to traditionalist gender ideology." (4)
- "'I would rather see my four girls shot and die as little girls who have faith in God than leave them to die some years later as godless, faithless, soulless Communists.'" (Pat Boone, 41)
- "[Marabel] Morgan offered practical tips to help women 'become the sunshine' in their homes, advice that included time management, more efficient meal planning (prepare your dinner salads right after breakfast), and weight loss. Most importantly, women just need to stop nagging their husbands." (60)
- "Morgan's solution was simple: treat your husband like a king, revere him, and cater to his every need. This was especially important for working women, because a man's 'masculinity may be threatened by your paycheck.' A wife needed to let her husband know that he was her hero, and it was her job to put her husband's 'tattered ego' back together at the end of each day by admiring his masculine qualities -- his muscles, or whiskers." (61)
- "In this way, proponents of 'biblical law' married 'traditional' gender roles to unrestrained, free-market capitalism. It was a match made in heaven." (76)
- "... the notion of personal rights interfered with the hierarchical structure of authority, contradicting God's design and provoking only anger and resentment." (76)
- "Men liked to 'hunt and fish and hike in the wilderness' while women preferred to 'stay at home and wait for them.' Men played sports as women watched, 'yawning on the sidelines.' But perhaps the most profound difference between men and women, according to Dobson, was their source of self-esteem: 'Men derive self-esteem by being *respected*; women feel worthy when they are *loved*.'" (83-84)
- "But family values politics was never about protecting the well-being of families generally. Fundamentally, evangelical 'family values' entailed the reassertion of patriarchal authority. At its most basic level, family values politics was about sex and power." (88)
- "Threats of a spiritual and cultural nature required a militant Christianity; threats to the nation required unrestrained militarism." (100)
- "... and for conservatives, 'tough on crime' generally connoted only certain types of crime: 'street crime,' or the threat of black men. Domestic violence, sexual assault, and child abuse didn't register." (105)
- "After all, as evangelicals saw it, the Cold War wasn't really all that different from the Wild West. Violence, or the threat of violence, secured order. Rules might have to be broken, but the ends justified the means. What was needed was a strong leader, a man who could assert masculine power in the international arena." (110-111)
- "Cole had no use for 'sissified' portraits of Jesus that failed to reveal his true character. '*Christlikeness and manhood are synonymous*,' he insisted, and to be Christlike, to be a man, required 'a certain ruthlessness.'" (125)
- "Women, children, churches, and nations all needed masculine decision makers; America was great only when its men were great." (125)
- "Falwell sparked controversy by characterizing AIDS as 'the wrath of God upon homosexuals' and recommending that those with AIDS be quarantined." (135)
- "Republicans wasted no time in impugning Dukakis's patriotism and sabotaging his masculinity -- and in their view the two were closely connected." (137)
- "Inspired by their interpretation of biblical prophecies in the Book of Revelation, conservative Protestants had long feared a 'one-world' government that would be ruled over by the Antichrist." (138)
- "Even worse, as a feminist and a career woman, Hillary Rodham had provoked the ire of religion conservatives when she refused to take her husband's name." (140)
- "Not only did this smack of socialism as far as conservatives were concerned, by the Christian Coalition insisted that health-care reform concealed a 'radical social agenda,' ostensibly by promoting abortion, gay rights, and sex education." (140)
- "Clinton's job rating received a significant boost as the scandal unfolded -- 'the formerly feminized president had been resurrected as a phallic leader.'" (144)
- "Within their own circles, evangelicals didn't have a strong record when it came to defending women against harassment and abuse." (144)
- "Without the threat of Godless communism to justify militant Christian masculinity, many evangelical men began to express uncertainty about what manhood in fact required." (149)
- "Unfortunately, the church was part of the problem. Failing to present the true Jesus, it instead depicted him 'as a meek and gentle milk-toast character' -- a man who never could have inspired 'brawny fishermen like Peter to follow him.' It was time to replace this 'Sunday school Jesus' with a warrior Jesus." (161)
- "'What if we told me up front that to join the church of Jesus Christ is ... to enlist in God's army and to place their lives on the line?'" (161)
- "As 'point man,' the father needed to protect sons from feminization. Boys, he explained, were naturally aggressive due to their higher levels of testosterone; aggression was 'part of being male.'" (163)
- "'They will survive the scars and broken bones of boyhood,' Farrar wrote, 'but they cannot survive being feminized.' Boys who were overprotected, particularly by mothers, were in danger of having their masculinity 'warped.'" (163)
- "God created men and women 'equal before God' yet 'distinct in their manhood in womanhood.' The statement attested that God had established male headship as part of the order of creation and closed the door to women in church leadership." (167)
- "As early as 1981, President Reagan began directing government funding to abstinence-only sex education ... Here was a case of government intrusion into the most intimate of matters, yet evangelicals didn't seem to mind." (171-172)
- "Yearning to know they were powerful and dangerous, someone to be reckoned with, they specialized in inventing games 'where bloodshed is a prerequisite for having fun.' God made men to be dangerous, Eldredge explained." (173)
- "According to Eldredge, God created all men to long for 'a battle to fight, an adventure to live, and a beauty to rescue.'" (174)
- "He praised Dabney's 'prophetic' views on the evils of public education and women's equality, and he found Dabney's anti-feminism 'refreshingly virile.' Phillips skirted around Dabney's proslavery sentiments, although Phillips, too, diminished the horrors of slavery and denied the genocide of Native Americans." (190)
- "In a language that would have been familiar to many among his flock, Driscoll insisted that real men avoided church because they had no interest in a 'Richard Simmons, hippie, queer Christ.'" (193)
- "For Driscoll, the problem went all the way back to the biblical Adam, a man who plunged humanity headlong into 'hell/feminism' by listening to his wife." (195)
- "Driscoll thrived on manufacturing a sense of threat posed by outsiders ... Driscoll incited fear in order to maintain control." (196)
- "'I remember being fascinated by the way that he would talk about things in the sermons no one was talking about, like how sex plays an important role in marriage, and how 'pussified' the church was becoming ... I didn't recognize the misogyny in his theology at the time, as a stereotypical beta male, it was like an invitation to become important ...'" (198)
- "Every man dies, but not every man truly lives." (217)
- "On the part of evangelical leaders, at the very least, fear of Islam appeared to be nothing more than an attempt to drum up support for the militant faith they were hawking." (218)
- "With books like the not-so-subtly titled *Why We Want to Kill You*, they positioned American Christians as victims, thereby justifying an extreme response. They accused any and all detractors of having ties to Islamic terrorism and used imagined threats of violence to bolster their own credibility." (225)
- "For these neocons, the military embodied the nation's highest ideals even as it unleashed violence and death, and there was no contradiction. War would provide Americans with "moral clarity." (230)
- *Duck Dynasty*, the reality television show featuring the Robertson family, debuted in 2008, and by 2013 it had become one of the most popular shows on television, with its fourth season premier drawing almost twelve million viewers, more than the highest viewed episodes of critical favorites *Breaking Bad* and *Mad Men* combined. (244-245)
- ""... social scientists identified a curious 'Trump effect.' Five years earlier, only 30 percent of white evangelicals believed that 'a person who commits an 'immoral' act could behave ethically in a public role.' The month before the [2016] election, 72 percent believed this was possible." (268)
- "Yet Piper himself had a less-than-stellar record when it came to dealing with abuse ... If her husband was asking her to engage in 'group sex or something really weird, bizarre, harmful,' then she might very gentle refuse to submit, but if the abuse was just hurting her and not requiring her to sin, then she should endure 'verbal abuse for a season' -- and 'perhaps being smacked one night.' Only then should she seek help ... from the church." (293)
- "A common sense of embattlement also links the rhetoric of the NRA to that of conservative white evangelicalism. For both, a bunker mentality strengthens identity and loyalty, and fuels militancy." (296)
- "Masculine authority, militarism, and the sexual and spiritual subordination of women have simply been part of the air evangelicals breathe for decades. In Sunday schools and Vacation Bible Schools boys learn to be superheroes for Christ, and girls to be beautiful princesses." (298)
- "With few exceptions, black men, Middle Eastern men, and Hispanic men are *not* called to wild, militant masculinity. Their aggression, by contrast, is seen as dangerous, a threat to the stability of home and nation." (301)
- "Militantly patriarchal expressions of the faith thrived in male-only discussion spaces, and so for some men, it was by listening to Christian women that the darker aspects of evangelical masculinity became visible." (302)

___

### *Let My People Go Surfing* - Yvon Chouinard

- "If we could all come to see our consumer products as tools that help us to live our real lives -- rather than as substitutes and surrogates for that life -- we would need many fewer products to be happy. (Naomi Klein, XI)
- "If you just ask people for help -- if you just admit that you don't know something -- they will fall all over themselves trying to help." (38)
- "Since we were the first catalog in the United States to use recycled paper, the result was a disaster the first season ... But in that first year alone our switching to recycled paper saved 3.5 million kilowatt-hours of electricity and 6 million gallons of water; kept 52,000 pounds of pollutants out of the air and 1,560 cubic yards of solid waste out of landfills, and prevented 14,500 trees from being felled." (57)
- "If you're really serious about giving money away, you'd sell the company for a hundred million or so, keep a couple million for yourselves, and put the rest in a foundation." (60)
- "The more you know, the less you need." (80)
- "The Dalai Lama says too much choice brings unhappiness." (86)
- "When I'm working on a problem, I never think about beauty. I think only how to solve the problem. But when I have finished, if the solution is not beautiful, I know it is wrong." (91)
- "Again, like the Zen approach to archery or anything else, you identify the goal and then forget about it and concentrate on the process." (117)
- "It's okay to be eccentric, as long as you are rich; otherwise, you're just crazy." (151)
- "A master in the art of living draws no sharp distinction between his work and his play ... to himself, he always appears to be doing both." (157)
- "Hiring people with diverse backgrounds brings in a flexibility of thought and openness to new ways of doing things, as opposed to hiring clones from business schools who have been taught a codified way of doing business. A business that thrives on being different requires different types of people." (159)
- "Allowing freedom to make mistakes and structuring opportunities for success gives children a sense of power over their environment that fuels self-esteem, independence, and problem solving." (163)
- "It's not the strongest species that survives, nor the most intelligent, but the one most responsive to change." (167)
- "The goal of climbing big, dangerous mountains should be to attain some sort of spiritual and personal growth, but this won't happen if you compromise away the entire process." (173)
- "He not busy being born is busy dying." (173)
- "I've found the cure for depression is action." (178)
- "The word 'sustainable' is another one of those words -- like 'gourmet,' and 'adventure' -- that have been so overused and misused as to become meaningless." (178)
- "Above all, admitting that I caused the mess and therefore I should clean it up is the best way to start living responsibly." (194)
- "But you are what you do, not what you say you are." (202)
- "Estimates vary, but even the low end of the spectrum suggests that a global switch to regenerative land husbandry would sequester our total annual emissions back underground. Which means we could reverse the trends of global warming simply by changing the way we farm and ranch." (215)
- "All of us working together can create the change that we need." (222)
- "You mean I'm the one who has to change?" (227)
- "Just because society is hell-bent on becoming so complex that we finally snooker ourselves into a corner with all our stuff, it doesn't mean we have to go there." (230)
- "I believe the way toward mastery of any endeavor is to work toward simplicity; replace complex technology with knowledge. The more you know, the less you need." (231)

___

### *The Masters: Golf, Money, and Power in Augusta, Georgia* - Curt Sampson

- "Perhaps the lesson is that maintaining a golf course is an unnatural act that can have unintended results." (224)
- "'I was assigned as an advisor to Lieutenant Colonel Nguyen Phong,' Woods said. 'Phong and I were in combat all the time. Because Phong fought like a tiger, I named my son Tiger in his honor.'" (233)

___

### *Why We Run: A Natural History* - Bernd Heinrich

- "... it turns out that what you have is less important than what you do with it." (83)
- "The mind leads, the body follow." (126)
- "Running is perhaps the most fundamental of all sports, and it is economically the least costly to perform. As a consequence, it is the most democratic and most competitive of all sports because individual merit can prevail despite economic inequality. It is a sport for everyone, the whole world over." (193)
- "Sure, it's genetic. But nobody could rationally propose that European women are not equally genetically endowed to be able to do precisely the same. They just don't have the same exposure to a culture that fosters the practice from very early childhood and then channels development ... Talent is not enough." (195)
- "The talent lies not in our genes but in our minds." (196)
- "Ultimately we are shaped by the anvil of our environment and the hammer of our mind, if used." (197)
- "To psych oneself up takes self-delusion ... At that point, one needs faith -- a combination of ignorance, deliberate blindness, hope, and optimism. It defies logic yet makes us able to strive and to survive." (250)
- "Now if you are going to win the battle, you have to do one thing. You have to make the mind run the body. Never let the body tell the mind what to do. The body will always give up. The body can only handle little steps. The mind can take great leaps." (254)
- "The cup is full. It contains what I had put into it. Like catching an antelope, the best things in life that we can experience are served on the challenge to endure and to overcome in the long run." (259)
- "One learns more from one's mistakes than from one's successes, and I therefore concentrate on them." (264)
- "Running has saved his life ... He had won big. His brain had done it. He thought he could do it, and did it. He could have been dead wrong. I also feel that I owe much to my running -- my education, my health, and maybe my life." (266)

___




























